Repository Metatavu/pakkasmarja-berries, pull requests merged in 2021-07, with the labels that each got.

#540 Feature 539 contract quantities endpoint
  scripts/kc-setup-for-tests.json
  src/rest/api/contracts.service.ts
  src/rest/application-roles.ts
  src/rest/impl/contracts.service.ts
  src/rest/model/contractQuantities.ts
  src/rest/model/models.ts
  src/test/contract-test.ts
  test-volumes/keycloak/kc.json
Labels: enhancement

#542 added new deliverystatus
  src/rest/impl/deliveryLoans.service.ts
  src/rest/model/body1.ts
  src/rest/model/deliveryStatus.ts
  src/rest/model/models.ts
Labels: enhancement

#535 Production update 18.6.2021
  docker/entrypoint.sh
  scripts/kc-setup-for-tests.json
  secured.tar.gz
  src/config/index.ts
  src/mailer/index.ts
  src/rest/api/contracts.service.ts
  src/rest/api/deliveryLoans.service.ts
  src/rest/application-roles.ts
  src/rest/impl/contracts.service.ts
  src/rest/impl/deliveries.service.ts
  src/rest/impl/deliveryLoans.service.ts
  src/rest/index.ts
  src/rest/model/body1.ts
  src/rest/model/contractQuantities.ts
  src/rest/model/deliveryStatus.ts
  src/rest/model/models.ts
  src/routes/sign-routes.ts
  src/sap/impl/deliveries.ts
  src/signature/index.ts
  src/tasks/index.ts
  src/test/contract-test.ts
  src/test/data/delivery-loan.json
  src/test/delivery-loans-test.ts
  test-volumes/keycloak/kc.json
  test-volumes/pakkasmarja-api/config.json
  test/config.json
Labels: bug, enhancement

#544 Production update 28.7.2021
  src/migration/migrations/36_deliveries_in_sap.ts
  src/models/index.ts
  src/rest/impl/deliveries.service.ts
  src/test/contract-test.ts
  src/test/data/delivery-notes-setup.sql
Labels: bug
