Repository Metatavu/pakkasmarja-berries, pull requests merged in 2021-06, with the labels that each got.

#513 Added remarks field to updateContract
  src/rest/impl/contracts.service.ts
Labels: bug

#514 Production update 02.06.2021
  src/rest/impl/contracts.service.ts
Labels: bug

#516 Added feature and refactored sap service implementations
  src/models/index.ts
  src/rest/impl/contracts.service.ts
  src/rest/impl/deliveries.service.ts
  src/rest/impl/operations.service.ts
  src/rest/model/operationType.ts
  src/sap/impl/contracts.ts
  src/sap/impl/deliveries.ts
  src/tasks/index.ts
  src/test/delivery-test.ts
Labels: enhancement

#517 Production update 03.06.2021 #2
  src/models/index.ts
  src/rest/impl/contracts.service.ts
  src/rest/impl/deliveries.service.ts
  src/rest/impl/operations.service.ts
  src/rest/model/operationType.ts
  src/sap/impl/contracts.ts
  src/sap/impl/deliveries.ts
  src/tasks/index.ts
  src/test/delivery-test.ts
Labels: enhancement

#518 Fixed item group fetch from models
  src/sap/impl/contracts.ts
  src/sap/service-layer-client/abstract-service.ts
  src/tasks/index.ts
Labels: enhancement

#519 Production update 03.06.2021 #3
  src/sap/impl/contracts.ts
  src/sap/service-layer-client/abstract-service.ts
  src/tasks/index.ts
Labels: enhancement

#520 Added missing brake
  src/rest/impl/operations.service.ts
Labels: bug

#521 Production update 03.06.2021 #4
  src/rest/impl/operations.service.ts
Labels: bug

#522 Added error messaging to delivery updates to SAP
  src/config/index.ts
  src/sap/impl/deliveries.ts
  src/tasks/index.ts
Labels: bug, enhancement

#523 Production update 04.06.2021
  src/config/index.ts
  src/sap/impl/deliveries.ts
  src/tasks/index.ts
Labels: bug, enhancement

#525 Production update 08.06.2021
  default-config.json
  docker-default-config.json
  src/rest/impl/deliveries.service.ts
  src/sap/impl/deliveries.ts
  src/tasks/index.ts
Labels: bug, enhancement

#526 fixed no products found in createNewSapContract
  secured.tar.gz
  src/config/index.ts
  src/rest/impl/deliveries.service.ts
  src/sap/impl/contracts.ts
  src/sap/impl/deliveries.ts
  src/sap/service-layer-client/abstract-service.ts
  src/sap/service-layer-client/services/contracts.service.ts
  src/sap/service-layer-client/services/purchaseDeliveryNotes.service.ts
  src/sap/service-layer-client/services/stockTransfers.service.ts
  src/sap/service-layer-client/types.ts
  src/tasks/index.ts
  src/test/contract-test.ts
  src/test/data/item-groups-setup.sql
  src/test/data/products-setup.sql
  src/test/data/products-teardown.sql
  test-volumes/pakkasmarja-api/config.json
  test/config.json
Labels: enhancement

#527 Production update 15.6.2021
  secured.tar.gz
  src/config/index.ts
  src/rest/impl/deliveries.service.ts
  src/sap/impl/contracts.ts
  src/sap/impl/deliveries.ts
  src/sap/service-layer-client/abstract-service.ts
  src/sap/service-layer-client/services/contracts.service.ts
  src/sap/service-layer-client/services/purchaseDeliveryNotes.service.ts
  src/sap/service-layer-client/services/stockTransfers.service.ts
  src/sap/service-layer-client/types.ts
  src/tasks/index.ts
  src/test/contract-test.ts
  src/test/data/item-groups-setup.sql
  src/test/data/products-setup.sql
  src/test/data/products-teardown.sql
  test-volumes/pakkasmarja-api/config.json
  test/config.json
Labels: enhancement

#529 Added batch number to purchase delivery note creation
  secured.tar.gz
  src/config/index.ts
  src/sap/impl/deliveries.ts
  src/sap/service-layer-client/types.ts
  src/test/delivery-test.ts
  test-volumes/pakkasmarja-api/config.json
  test/config.json
Labels: enhancement

#530 Production update 16.6.2021
  secured.tar.gz
  src/config/index.ts
  src/sap/impl/deliveries.ts
  src/sap/service-layer-client/types.ts
  src/test/delivery-test.ts
  test-volumes/pakkasmarja-api/config.json
  test/config.json
Labels: enhancement

#532 Feature 531 stock transfers for berry boxes
  secured.tar.gz
  src/rest/api/deliveryLoans.service.ts
  src/rest/impl/deliveries.service.ts
  src/rest/impl/deliveryLoans.service.ts
  src/rest/index.ts
  src/sap/impl/deliveries.ts
  src/test/data/delivery-loan.json
  src/test/delivery-loans-test.ts
  test-volumes/pakkasmarja-api/config.json
  test/config.json
Labels: enhancement

#534 Feature 533 contract to sap also after signing
  src/mailer/index.ts
  src/rest/impl/contracts.service.ts
  src/routes/sign-routes.ts
  src/sap/impl/deliveries.ts
  src/signature/index.ts
  src/tasks/index.ts
Labels: enhancement
